apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apiadmin.fullname" . }}-config
  labels:
    {{- include "apiadmin.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}

