apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apiadmin.fullname" . }}-secret
  labels:
    {{- include "apiadmin.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}


